name: deploy to Azure slot and switch

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: azure-ds-test
  AZURE_WEBAPP_SLOT_NAME: staging
  NODE_VERSION: "18.12.0" # set this to the node version to use
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  BE_ARTIFACT_NAME: backend-app
  BE_ZIP_NAME: backend-app.zip


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      #
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      #
      - name: Build backend
        run: npm ci
      #
      - name: Create zip for backend artifact
        run: zip -r ${{ env.BE_ZIP_NAME }} bin node_modules public routes views app.js package.json package-lock.json
      #
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BE_ARTIFACT_NAME }}
          path: ${{ env.BE_ZIP_NAME }}
          retention-days: 14

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: 'staging'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BE_ARTIFACT_NAME }}
      #
      - name: Unzip artifact
        run: unzip ${{ env.BE_ZIP_NAME }}
      #
      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
